project:
  type: website

website:
  title: "choi seongbin."
  navbar:
    background: rgb(255,255,255) 
    left:
      - text: Home 
        href: https://shengbcui.github.io/
      - text: About 
        href: https://shengbcui.github.io/#about 
      - text: Research 
        href: https://shengbcui.github.io/#research
      - text: Publications
        href: https://shengbcui.github.io/#pubs 
      - text: Music
        href: https://shengbcui.github.io/#music
      - text: Contact 
        href: https://shengbcui.github.io/#contact
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

